project_id = "prjpwppabelirtiwssus"

[functions.mapbox-geocode]
verify_jwt = false

[functions.mapbox-directions]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-pdv-user]
verify_jwt = false